version: "3.8"

services:
  vue-app:
    build:
      context: .

    ports:
      - "3000:3000"

    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./
          target: /app
          action: sync

 